// apps/compare/src/components/TextFieldCompare.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { TextField } from '@misaki-mei/heroui-vue'

const username = ref('')
const bio = ref('')
const isUsernameInvalid = computed(() => username.value.length > 0 && username.value.length < 3)
const isBioInvalid = computed(() => bio.value.length > 0 && bio.value.length < 20)
</script>

<template>
  <div>
    <section class="compare-section">
      <h3 class="compare-section__title">Basic</h3>
      <div style="display: flex; flex-direction: column; gap: 1rem">
        <TextField name="email" type="email" label="Email" placeholder="Enter your email" />
        <TextField
          name="username"
          label="Username"
          placeholder="jane_doe"
          description="Choose a unique username for your account"
        />
      </div>
    </section>

    <section class="compare-section">
      <h3 class="compare-section__title">Required</h3>
      <TextField
        is-required
        name="fullName"
        label="Full Name"
        placeholder="John Doe"
        description="This field is required"
      />
    </section>

    <section class="compare-section">
      <h3 class="compare-section__title">Disabled & Invalid</h3>
      <div style="display: flex; flex-direction: column; gap: 1rem">
        <TextField
          is-disabled
          name="accountId"
          label="Account ID"
          placeholder="Auto-generated"
          description="This field cannot be edited"
          model-value="USR-12345"
        />
        <TextField
          is-invalid
          is-required
          name="password"
          type="password"
          label="Password"
          error="Password must be longer than 8 characters"
        />
      </div>
    </section>

    <section class="compare-section">
      <h3 class="compare-section__title">Validation (controlled)</h3>
      <div style="display: flex; flex-direction: column; gap: 1rem">
        <TextField
          is-required
          :is-invalid="isUsernameInvalid"
          name="username"
          label="Username"
          placeholder="jane_doe"
          :error="isUsernameInvalid ? 'Username must be at least 3 characters.' : ''"
          :description="!isUsernameInvalid ? 'Choose a unique username for your profile.' : ''"
          :model-value="username"
          @update:model-value="(v: string | number) => (username = String(v))"
        />

        <TextField
          is-required
          :is-invalid="isBioInvalid"
          name="bio"
          label="Bio"
          placeholder="Tell us about yourself..."
          :error="isBioInvalid ? 'Bio must contain at least 20 characters.' : ''"
          :description="!isBioInvalid ? `Minimum 20 characters (${bio.length}/20).` : ''"
          :model-value="bio"
          @update:model-value="(v: string | number) => (bio = String(v))"
        />
      </div>
    </section>
  </div>
</template>

// apps/compare/src/components/TextFieldCompare.react.tsx
import { Description, FieldError, Input, Label, TextArea, TextField } from '@heroui/react'
import { useState } from 'react'

export function TextFieldCompare() {
  const [username, setUsername] = useState('')
  const [bio, setBio] = useState('')
  const isUsernameInvalid = username.length > 0 && username.length < 3
  const isBioInvalid = bio.length > 0 && bio.length < 20

  return (
    <div>
      <section className="compare-section">
        <h3 className="compare-section__title">Basic</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <TextField className="w-full max-w-64" name="email" type="email">
            <Label>Email</Label>
            <Input placeholder="Enter your email" />
          </TextField>
          <TextField className="w-full max-w-64" name="username">
            <Label>Username</Label>
            <Input placeholder="jane_doe" />
            <Description>Choose a unique username for your account</Description>
          </TextField>
        </div>
      </section>

      <section className="compare-section">
        <h3 className="compare-section__title">Required</h3>
        <TextField isRequired className="w-full max-w-64" name="fullName">
          <Label>Full Name</Label>
          <Input placeholder="John Doe" />
          <Description>This field is required</Description>
        </TextField>
      </section>

      <section className="compare-section">
        <h3 className="compare-section__title">Disabled & Invalid</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <TextField isDisabled className="w-full max-w-64" name="accountId" value="USR-12345">
            <Label>Account ID</Label>
            <Input placeholder="Auto-generated" />
            <Description>This field cannot be edited</Description>
          </TextField>
          <TextField isInvalid isRequired className="w-full max-w-64" name="password" type="password">
            <Label>Password</Label>
            <Input />
            <FieldError>Password must be longer than 8 characters</FieldError>
          </TextField>
        </div>
      </section>

      <section className="compare-section">
        <h3 className="compare-section__title">Validation (controlled)</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <TextField
            isRequired
            isInvalid={isUsernameInvalid}
            name="username"
            value={username}
            onChange={setUsername}
          >
            <Label>Username</Label>
            <Input placeholder="jane_doe" />
            {isUsernameInvalid ? (
              <FieldError>Username must be at least 3 characters.</FieldError>
            ) : (
              <Description>Choose a unique username for your profile.</Description>
            )}
          </TextField>

          <TextField isRequired isInvalid={isBioInvalid} name="bio" value={bio} onChange={setBio}>
            <Label>Bio</Label>
            <TextArea placeholder="Tell us about yourself..." />
            {isBioInvalid ? (
              <FieldError>Bio must contain at least 20 characters.</FieldError>
            ) : (
              <Description>Minimum 20 characters ({bio.length}/20).</Description>
            )}
          </TextField>
        </div>
      </section>
    </div>
  )
}
